#!/bin/bash
# TASK 4 - Collaboration: be up to date
# -----------------------------------------------

cd /alche-zero_day/git

git pull origin master

echo "git pull origin master" > up_to_date

git add .
git status
git commit -m "How to be up to date in git"
git push origin master


